Refactor/refactor svg icon
Lipoic/Lipoic-Frontend pull request #138
Opened 2022-06-27 23:21 UTC by a3510377

# Description

refactor svg icon
feat: add func

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changesh my changes

2022-06-27 23:53 UTC, a3510377 commented
done

2022-07-06 02:08 UTC, SiongSng requested changes

2022-07-06 02:08 UTC, SiongSng commented on src/utils/Object.ts
> +export const DictOmit = <T extends Record<keyType, any>, K extends keyType>(
這個函式的用途是?
沒看到任何地方有用到

2022-07-06 02:51 UTC, a3510377 commented on src/utils/Object.ts
> +export const DictOmit = <T extends Record<keyType, any>, K extends keyType>(
基於 typescript Omit，函數實例

2022-07-06 02:55 UTC, a3510377 commented on src/utils/Object.ts
> +export const DictOmit = <T extends Record<keyType, any>, K extends keyType>(
```ts
const t = {
  a: 'a',
  b: 'b',
};
const a = DictOmit(t, 'a');
// a => {
//   b: 'b'
// }
```

2022-07-06 02:56 UTC, SiongSng commented on src/utils/Object.ts
> +export const DictOmit = <T extends Record<keyType, any>, K extends keyType>(
ok :+1: 
但我看好像沒其他地方調用 (call) 到這個 function，可以刪除嗎？

2022-07-26 13:23 UTC, SiongSng commented on src/utils/Object.ts
> +export const DictOmit = <T extends Record<keyType, any>, K extends keyType>(
@a3510377 所以你覺得如何? .w.

2022-07-26 13:45 UTC, a3510377 commented on src/utils/Object.ts
> +export const DictOmit = <T extends Record<keyType, any>, K extends keyType>(
痾就留著八原本有用到所以寫出來的以後應該還會用到

2022-08-23 10:19 UTC, SiongSng approved these changes
LGTM

2022-08-23 10:21 UTC, merged