Feature/overview
Lipoic/Lipoic-Frontend pull request #255
Opened 2022-12-24 03:48 UTC by MRHACO

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

# Checklist:

- [✓] My code follows the style guidelines of this project
- [✓] I have performed a self-review of my code
- [✓] I have commented my code, particularly in hard-to-understand areas
- [✓] I have made corresponding changes to the documentation
- [✓] My changes generate no new warnings
- [✓] I have added tests that prove my fix is effective or that my feature works
- [✓] New and existing unit tests pass locally with my changes

2022-12-24 07:26 UTC, SiongSng requested changes

2022-12-24 07:26 UTC, SiongSng commented on package.json
> +    "@material/web": "^0.1.0-alpha.0",
沒有用到的套件可以刪除

2022-12-24 07:26 UTC, SiongSng commented on src/stores/models/settings.ts
> +      console.log('theme', theme);
應該不用 console.log 主題吧

2022-12-24 07:28 UTC, SiongSng commented
目前主要還缺單元測試、手機端的 nav bar 動畫、還有手機端的淺色主題

2023-01-04 10:09 UTC, SiongSng commented
目前應該就單元測試與手機端的上課通知

2023-01-04 10:23 UTC, SiongSng requested changes
我剛才稍微掃了一下程式碼，發現的幾個問題

2023-01-04 10:23 UTC, SiongSng commented on src/components/overview/OverviewLayout.vue
> +  <div class="hidden w-[100%] phone:inline-block">
或許這裡的佈局邏輯可以更一致一點

上方是如果是手機端就隱藏
下方則是預設隱藏，如果是手機端就顯示

2023-01-04 10:23 UTC, SiongSng commented on src/components/overview/desktop/AppBar.vue
> +    <div class="mt-7 flex-1 text-right">
如果切換主題這部份有 tooltip 應該可以讓使用者更了解這些按鈕的用途

2023-01-04 10:23 UTC, SiongSng commented on src/components/overview/desktop/AppBar.vue
> +      <button id="account" class="mx-[48px]">
目前後端已經實做了頭貼 API，所以這裡可以串接使用者實際的頭貼，如果沒有頭貼才換成這個 icon

2023-01-04 10:23 UTC, SiongSng commented on src/components/overview/desktop/RecentCard.vue
> +    <img :src="'src/assets/overview/' + props.name + '.png'" />
這裡或許可以用 `import()` 來處理圖片路徑的部份

2023-01-04 10:23 UTC, SiongSng commented on src/components/overview/desktop/SideBar.vue
> +    icon: `
這些導航列的 icon 應該可以讓手機端與桌機共用，就不用重複寫相同的程式碼

2023-01-04 10:23 UTC, SiongSng commented on src/components/overview/mobile/AppBar.vue
> +      <button id="account" class="mr-5 block">
這裡與桌面端的串接使用者頭貼 API 相同

2023-01-04 10:23 UTC, SiongSng commented on src/stores/models/settings.ts
> +  theme: string;
建議這裡可以弄 `enum` 枚舉這類的東西去定義

2023-01-23 14:54 UTC, SiongSng commented on src/components/overview/desktop/AppBar.vue
> +      <button id="account" class="mx-[48px]">
@MRHACO  預計挪到另一個分支處理

2023-01-24 14:24 UTC, MRHACO commented on src/components/overview/desktop/RecentCard.vue
> +    <img :src="'src/assets/overview/' + props.name + '.png'" />
import 必須在最頂層
宣告props後即無法使用

2023-02-03 10:42 UTC, SiongSng requested changes
由於是切版，大多實際功能尚未實做
因此暫時不須單元測試使用者介面的部份，但有部份邏輯上仍需要測試，像是 settings store
我等下會幫忙寫一下#

2023-02-03 11:07 UTC, SiongSng requested changes

2023-02-03 11:07 UTC, SiongSng commented on src/locales/zh-TW.json
> +  "overview": {
這裡目前沒有使用到 應該先不用加進去吧

2023-02-04 06:30 UTC, SiongSng approved these changes
LGTM

2023-02-04 06:31 UTC, merged