feat: auth page structure
Lipoic/Lipoic-Frontend pull request #283
Opened 2023-03-08 12:41 UTC by banahaker

# Description

I don't know wtf is our file structure for auth pages such as `BlockLoginPage`, `BlockSignUpPage` etc.
Obviously, those components is a PAGE not a BLOCK, so I change the structure of that.

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] New and existing unit tests pass locally with my changes

2023-03-08 13:43 UTC, SiongSng requested changes

2023-03-08 13:43 UTC, SiongSng commented on src/router/index.ts
> +        component: () => import('@/pages/Home/LoginPage.vue'),
話說這個東西不是在 `Account` 底下嗎？
怎麼會是用 `Home`

2023-03-08 23:13 UTC, banahaker commented on src/router/index.ts
> +        component: () => import('@/pages/Home/LoginPage.vue'),
因為你們account 這個頁面的檔案名寫HomePage

2023-03-11 03:33 UTC, SiongSng commented on src/router/index.ts
> +        component: () => import('@/pages/Home/LoginPage.vue'),
沒有吧

2023-03-22 15:02 UTC, SiongSng approved these changes
LGTM

2023-03-22 15:03 UTC, merged