feat: create login page
Lipoic/Lipoic-Frontend pull request #51
Opened 2022-05-15 15:15 UTC by banahaker

# [ NEW FEATURE ] Login Page

create login page for lipoic web

Fixes #43 

## Type of change
- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-05-16 05:04 UTC, banahaker commented
LOG: daloa @a3510377 write a perfect code

2022-05-16 08:16 UTC, banahaker commented
i built the base, then i'll  better them, i'm going on!

2022-05-17 07:58 UTC, banahaker commented on src/components/BlockSignUpPage.vue
> +<template>sign up</template>
resolved !

2022-05-17 12:10 UTC, SiongSng requested changes

2022-05-17 12:10 UTC, SiongSng commented on src/MainApp.vue
> +const setStyle = (key: `--${string}`, value: string | null) =>
Please add comments

2022-05-17 12:10 UTC, SiongSng commented on src/components/BlockLoginPage.vue
> +  { title: '臺灣雲端教育雲帳號', img: 'login-taiwanOpenId' },
Missing i18n

2022-05-17 12:10 UTC, SiongSng commented on src/scss/global.scss
>  $MainColor: $MainColor;
```suggestion
```

2022-05-17 12:10 UTC, SiongSng commented on src/locales/zh-CN.json
> +  "auth.login.usernameInput": "使用者名称",
```suggestion
  "auth.login.usernameInput": "用户名称",
```

2022-05-17 12:23 UTC, banahaker commented on src/components/BlockLoginPage.vue
> +  { title: '臺灣雲端教育雲帳號', img: 'login-taiwanOpenId' },
1. why `Google` and `FaceBook` need i18n?
2. why `臺灣雲端教育帳號` need a English or is it have one?

2022-05-17 12:31 UTC, SiongSng commented on src/components/BlockLoginPage.vue
> +  { title: '臺灣雲端教育雲帳號', img: 'login-taiwanOpenId' },
Taiwan Cloud Education?

2022-05-17 14:04 UTC, SiongSng approved these changes
LGTM!

2022-05-17 14:04 UTC, merged