Feat/add stylelint config
Lipoic/Lipoic-Frontend pull request #65
Opened 2022-05-28 00:59 UTC by a3510377

# Description

feat stylelint config

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-05-28 13:02 UTC, SiongSng requested changes
There is a problem with the animation of the home page
https://user-images.githubusercontent.com/48402225/170826684-b3962b3b-60fe-4ee6-ab7f-fccbe2f882ab.mp4

2022-05-28 13:16 UTC, a3510377 commented
done

2022-05-29 05:44 UTC, SiongSng requested changes

2022-05-29 05:44 UTC, SiongSng commented on .vscode/extensions.json
> +    "vue.volar",
Please do not modify the ID of the extension

2022-05-29 06:15 UTC, SiongSng requested changes

2022-05-29 06:15 UTC, SiongSng commented on .vscode/extensions.json
> +    "lokalise.i18n-ally",
Please do not modify the ID of the extension

2022-05-29 06:20 UTC, a3510377 commented on .vscode/extensions.json
> +    "lokalise.i18n-ally",
這才是對的Emm
lokalise.i18n-ally

2022-05-29 09:47 UTC, a3510377 commented
done

2022-05-29 10:33 UTC, SiongSng approved these changes
LGTM!

2022-05-29 10:33 UTC, merged