Feat/add axios
Lipoic/Lipoic-Frontend pull request #71
Opened 2022-05-29 02:51 UTC by a3510377

# Description

add axios & config

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-05-29 04:46 UTC, SiongSng requested changes

2022-05-29 04:46 UTC, SiongSng commented on .eslintrc.js
> +    'import/no-extraneous-dependencies': 'off',
請不要隨意修改 eslint 的設定

2022-05-29 04:46 UTC, SiongSng commented on .vscode/settings.json
> +  "files.eol": "\n"
what is eol?

2022-05-29 05:44 UTC, a3510377 commented on .eslintrc.js
> +    'import/no-extraneous-dependencies': 'off',
![image](https://user-images.githubusercontent.com/70706886/170854076-5bce0caf-d8f1-43e1-b5e6-2c98edea3e4c.png)
ㄊ他會和 vue 的 path 衝突

2022-05-29 06:23 UTC, SiongSng commented on .eslintrc.js
> +    'import/no-extraneous-dependencies': 'off',
那你把那個放在獨立的檔案裡面，不要全域停用

2022-06-08 09:00 UTC, SiongSng requested changes

2022-06-08 09:00 UTC, SiongSng commented on .editorconfig
> +end_of_line = lf # end of line / 設定換行類型 ( lf | cr | crlf )
```suggestion

```

2022-06-08 09:00 UTC, SiongSng commented on .eslintrc.js
> +    // no-param-reassign
Please do not modify ESLint config.

2022-06-08 09:00 UTC, SiongSng commented on src/configs/http.ts
> +  /** request headers | 請求標頭 */
Do not use Chinese comments in the code

2022-06-08 09:00 UTC, SiongSng commented on src/configs/index.ts
> +  debugServer: boolean;
I don't think we need to send error reports to the server, right?

2022-06-12 14:34 UTC, SiongSng commented
![](https://github.trello.services/images/mini-trello-icon.png) [前端串連帳號系統 API](https://trello.com/c/sE7IVivc/1-%E5%89%8D%E7%AB%AF%E4%B8%B2%E9%80%A3%E5%B8%B3%E8%99%9F%E7%B3%BB%E7%B5%B1-api)

2022-06-27 03:41 UTC, SiongSng requested changes

2022-06-27 03:41 UTC, SiongSng commented on src/components/header/UserInfoHeader.vue
> +const menuState = ref<undefined | ''>(undefined);
應該有更好處理 menu 的作法?
例如用 boolean 搭配 css

2022-06-27 03:41 UTC, SiongSng commented on src/http/index.ts
> +      config.token = token;
```suggestion
```
直接從 store/config 取 token 就好，不必再設定一次

2022-06-27 08:16 UTC, SiongSng approved these changes
LGTM

2022-06-27 09:10 UTC, banahaker approved these changes
Nice PR

2022-06-27 09:27 UTC, merged