perf: better performance
Lipoic/Lipoic-Frontend pull request #82
Opened 2022-05-30 09:43 UTC by SiongSng

Co-authored-by: 猴子 <a3510377@users.noreply.github.com>
Co-authored-by: flyingeasy <flyingeasy@users.noreply.github.com>

# Description

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-05-31 05:43 UTC, a3510377 commented
...手殘案到..

2022-05-31 09:25 UTC, SiongSng commented on package.json
> -    "happy-dom": "4.1.0",
why remove happy-dom?

2022-06-06 10:34 UTC, SiongSng reviewed
LGTM

2022-06-06 11:32 UTC, banahaker requested changes
Not bad but something wrong

2022-06-06 11:32 UTC, banahaker commented on package.json
> -    "happy-dom": "4.1.0",
cause it's not used

2022-06-06 11:32 UTC, banahaker commented on .editorconfig
> +end_of_line = lf # end of line / 文件行尾格式 ( lf | crlf )
註解確定要中英夾雜了嗎

2022-06-06 11:32 UTC, banahaker commented on src/scss/global.scss
> -// Font - Roboto
why delete those

2022-06-06 11:33 UTC, SiongSng commented on src/scss/global.scss
> -// Font - Roboto
節省效能

2022-06-06 11:37 UTC, banahaker approved these changes
great

2022-06-06 11:37 UTC, banahaker commented
may not has big problem

2022-06-08 12:29 UTC, merged